#!/usr/bin/env python3
"""Turn the AArch64 sleigh data files into a C++ translation unit.

The Ghidra decompiler loads its language definition from disk at runtime. That
would mean shipping a directory next to the binary, which defeats the point of
static linking, so the files are compiled in instead and unpacked to a scratch
directory on first use. AArch64 alone is about 570 KB, which is cheap enough to
carry.

Usage: embed_sleigh.py <sleigh-dir> <output.cpp>
"""

import os
import sys


def main() -> int:
    if len(sys.argv) != 3:
        print(__doc__, file=sys.stderr)
        return 2
    src_dir, out_path = sys.argv[1], sys.argv[2]

    names = sorted(
        n for n in os.listdir(src_dir)
        if n.endswith((".sla", ".cspec", ".ldefs", ".pspec"))
    )
    if not names:
        print(f"no sleigh files in {src_dir}", file=sys.stderr)
        return 1

    with open(out_path, "w") as out:
        out.write(
            "// Generated by cross/embed_sleigh.py -- do not edit.\n"
            '#include "sleigh_data.h"\n\n'
            "namespace sleigh_data {\nnamespace {\n\n"
        )

        total = 0
        for i, name in enumerate(names):
            with open(os.path.join(src_dir, name), "rb") as f:
                blob = f.read()
            total += len(blob)
            out.write(f"// {name} ({len(blob)} bytes)\n")
            out.write(f"const unsigned char kFile{i}[] = {{")
            for j, byte in enumerate(blob):
                if j % 20 == 0:
                    out.write("\n    ")
                out.write(f"{byte},")
            out.write("\n};\n\n")

        out.write("const File kFilesArray[] = {\n")
        for i, name in enumerate(names):
            out.write(f'    {{"{name}", kFile{i}, sizeof(kFile{i})}},\n')
        out.write("};\n\n} // namespace\n\n")
        out.write(
            "const File *files() { return kFilesArray; }\n"
            "size_t file_count() { return sizeof(kFilesArray) / sizeof(kFilesArray[0]); }\n\n"
            "} // namespace sleigh_data\n"
        )

    print(f"embedded {len(names)} files, {total} bytes -> {out_path}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
